### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by bkocamantr** [fireFoam-dev/fireFoam-v1912#16]
I tried installing as instructed. I get the following errors:
./fireFoam_setup.bash: line 55: git: command not found
./fireFoam_setup.bash: line 56: cd: OpenFOAM-v1912: No such file or directory
./fireFoam_setup.bash: line 57: git: command not found
./fireFoam_setup.bash: line 68: git: command not found
./fireFoam_setup.bash: line 76: cd: /home/bora/FM-public-FF/OpenFOAM-v1912: No such file or directory
./fireFoam_setup.bash: line 79: git: command not found
./fireFoam_setup.bash: line 24: /home/bora/FM-public-FF/OpenFOAM-v1912/etc/bashrc: No such file or directory
./fireFoam_setup.bash: line 91: ./Allwmake: No such file or directory
./fireFoam_setup.bash: line 24: /home/bora/FM-public-FF/OpenFOAM-v1912/etc/bashrc: No such file or directory
./fireFoam_setup.bash: line 103: ./Allwmake: No such file or directory
./fireFoam_setup.bash: line 24: /home/bora/FM-public-FF/OpenFOAM-v1912/etc/bashrc: No such file or directory
./fireFoam_setup.bash: line 112: cd: /home/bora/FM-public-FF/fireFoam-v1912: No such file or directory
./fireFoam_setup.bash: line 115: ./Allwmake: No such file or directory

Can you help me resolve the issue?

**Comment by danmohad** [comment]
Considering this first line:
`./fireFoam_setup.bash: line 55: git: command not found`
It seems that the shell in which you executed `fireFoam_setup.bash` doesn't have `git` installed. You will need `git`, along with the [minimum requirements for OpenFOAM](https://www.openfoam.com/documentation/system-requirements)

**Comment by bkocamantr** [comment]
Hi Danyal,

Thank you for the warning. I will install it and try again.

I will also install other dependencies but I already installed openfoam
version 2406 so I think most of them are already installed.

Best regards

Bora

Danyal Mohaddes ***@***.***>, 7 Kas 2024 Per, 20:46 tarihinde
şunu yazdı:

**Comment by bkocamantr** [comment]
Hi Danyal,

When I run the ./mesh.sh command in poolfireMcCaffrey case, I get "./mesh.sh: 13: Syntax error: Bad for loop variable" error. Should I ignore this error or is a correction needed running the case?

Thank you.

Kind regards

Bora Kocaman

**Comment by danmohad** [comment]
Probably a shell issue. Try changing [this line](https://github.com/fireFoam-dev/fireFoam-v1912/blob/4cf57cef69ba5fbf3c516248e404ec7e3833f7b7/tutorials/poolfireMcCaffrey/mesh.sh#L1) to `#!/bin/bash`

**Comment by bkocamantr** [comment]
Changed it and it worked! Thank you Danyal. Will run the case next.

Kind regards,

Bora Kocaman
